project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  page-navigation: false
  page-footer: 
    center: Built with <a href="https://quarto.org" target="_blank">Quarto.</a> Template design inspired by <a href="https://nerfies.github.io/" target="_blank">Nerfies.</a>
  
format:
  html:
    theme: [cosmo, fonts.scss]
    css: styles.css
    toc: false
    smooth-scroll: true
    search: false